CREATE OR REPLACE FUNCTION test_data_countries() --FF NEW
RETURNS boolean AS $$
DECLARE

success BOOLEAN:=FALSE;

BEGIN

  PERFORM common_create_country (1, true, 'United States', 'US');
  PERFORM common_create_country (2, true, 'Canada', 'CA');
  PERFORM common_create_country (3, true, 'Afghanistan', 'AF');
  PERFORM common_create_country (4, true, 'Albania', 'AL');
  PERFORM common_create_country (5, true, 'Algeria', 'DZ');
  PERFORM common_create_country (6, true, 'American Samoa', 'AS');
  PERFORM common_create_country (7, true, 'Andorra', 'AD');
  PERFORM common_create_country (8, true, 'Angola', 'AO');
  PERFORM common_create_country (9, true, 'Anguilla', 'AI');
  PERFORM common_create_country (10, true, 'Antarctica', 'AQ');
  PERFORM common_create_country (11, true, 'Antigua and Barbuda', 'AG');
  PERFORM common_create_country (12, true, 'Argentina', 'AR');
  PERFORM common_create_country (13, true, 'Armenia', 'AM');
  PERFORM common_create_country (14, true, 'Aruba', 'AW');
  PERFORM common_create_country (15, true, 'Australia', 'AU');
  PERFORM common_create_country (16, true, 'Austria', 'AT');
  PERFORM common_create_country (17, true, 'Azerbaijan', 'AZ');
  PERFORM common_create_country (18, true, 'Bahamas', 'BS');
  PERFORM common_create_country (19, true, 'Bahrain', 'BH');
  PERFORM common_create_country (20, true, 'Bangladesh', 'BD');
  PERFORM common_create_country (21, true, 'Barbados', 'BB');
  PERFORM common_create_country (22, true, 'Belarus', 'BY');
  PERFORM common_create_country (23, true, 'Belgium', 'BE');
  PERFORM common_create_country (24, true, 'Belize', 'BZ');
  PERFORM common_create_country (25, true, 'Benin', 'BJ');
  PERFORM common_create_country (26, true, 'Bermuda', 'BM');
  PERFORM common_create_country (27, true, 'Bhutan', 'BT');
  PERFORM common_create_country (28, true, 'Bolivia', 'BO');
  PERFORM common_create_country (29, true, 'Bosnia and Herzegovina', 'BA');
  PERFORM common_create_country (30, true, 'Botswana', 'BW');
  PERFORM common_create_country (31, true, 'Bouvet Island', 'BV');
  PERFORM common_create_country (32, true, 'Brazil', 'BR');
  PERFORM common_create_country (33, true, 'British Indian Ocean Territory', 'IO');
  PERFORM common_create_country (34, true, 'Brunei Darussalam', 'BN');
  PERFORM common_create_country (35, true, 'Bulgaria', 'BG');
  PERFORM common_create_country (36, true, 'Burkina Faso', 'BF');
  PERFORM common_create_country (37, true, 'Burundi', 'BI');
  PERFORM common_create_country (38, true, 'Cambodia', 'KH');
  PERFORM common_create_country (39, true, 'Cameroon', 'CM');
  PERFORM common_create_country (40, true, 'Cape Verde', 'CV');
  PERFORM common_create_country (41, true, 'Cayman Islands', 'KY');
  PERFORM common_create_country (42, true, 'Central African Republic', 'CF');
  PERFORM common_create_country (43, true, 'Chad', 'TD');
  PERFORM common_create_country (44, true, 'Chile', 'CL');
  PERFORM common_create_country (45, true, 'China', 'CN');
  PERFORM common_create_country (46, true, 'Christmas Island', 'CX');
  PERFORM common_create_country (47, true, 'Cocos (Keeling) Islands', 'CC');
  PERFORM common_create_country (48, true, 'Colombia', 'CO');
  PERFORM common_create_country (49, true, 'Comoros', 'KM');
  PERFORM common_create_country (50, true, 'Congo', 'CG');
  PERFORM common_create_country (51, true, 'Congo, The Democratic Republic of The', 'CD');
  PERFORM common_create_country (52, true, 'Cook Islands', 'CK');
  PERFORM common_create_country (53, true, 'Costa Rica', 'CR');
  PERFORM common_create_country (54, true, 'Cote D ivoire', 'CI');
  PERFORM common_create_country (55, true, 'Croatia', 'HR');
  PERFORM common_create_country (56, true, 'Cuba', 'CU');
  PERFORM common_create_country (57, true, 'Cyprus', 'CY');
  PERFORM common_create_country (58, true, 'Czech Republic', 'CZ');
  PERFORM common_create_country (59, true, 'Denmark', 'DK');
  PERFORM common_create_country (60, true, 'Djibouti', 'DJ');
  PERFORM common_create_country (61, true, 'Dominica', 'DM');
  PERFORM common_create_country (62, true, 'Dominican Republic', 'DO');
  PERFORM common_create_country (63, true, 'East Timor', 'TL');
  PERFORM common_create_country (64, true, 'Ecuador', 'EC');
  PERFORM common_create_country (65, true, 'Egypt', 'EG');
  PERFORM common_create_country (66, true, 'El Salvador', 'SV');
  PERFORM common_create_country (67, true, 'Equatorial Guinea', 'GQ');
  PERFORM common_create_country (68, true, 'Eritrea', 'ER');
  PERFORM common_create_country (69, true, 'Estonia', 'EE');
  PERFORM common_create_country (70, true, 'Ethiopia', 'ET');
  PERFORM common_create_country (71, true, 'Falkland Islands (Malvinas)', 'FK');
  PERFORM common_create_country (72, true, 'Faroe Islands', 'FO');
  PERFORM common_create_country (73, true, 'Fiji', 'FJ');
  PERFORM common_create_country (74, true, 'Finland', 'FI');
  PERFORM common_create_country (75, true, 'France', 'FR');
  PERFORM common_create_country (76, true, 'French Guiana', 'GF');
  PERFORM common_create_country (77, true, 'French Polynesia', 'PF');
  PERFORM common_create_country (78, true, 'French Southern Territories', 'TF');
  PERFORM common_create_country (79, true, 'Gabon', 'GA');
  PERFORM common_create_country (80, true, 'Gambia', 'GM');
  PERFORM common_create_country (81, true, 'Georgia', 'GE');
  PERFORM common_create_country (82, true, 'Germany', 'DE');
  PERFORM common_create_country (83, true, 'Ghana', 'GH');
  PERFORM common_create_country (84, true, 'Gibraltar', 'GI');
  PERFORM common_create_country (85, true, 'Greece', 'GR');
  PERFORM common_create_country (86, true, 'Greenland', 'GL');
  PERFORM common_create_country (87, true, 'Grenada', 'GD');
  PERFORM common_create_country (88, true, 'Guadeloupe', 'GP');
  PERFORM common_create_country (89, true, 'Guam', 'GU');
  PERFORM common_create_country (90, true, 'Guatemala', 'GT');
  PERFORM common_create_country (91, true, 'Guinea', 'GN');
  PERFORM common_create_country (92, true, 'Guinea-Bissau', 'GW');
  PERFORM common_create_country (93, true, 'Guyana', 'GY');
  PERFORM common_create_country (94, true, 'Haiti', 'HT');
  PERFORM common_create_country (95, true, 'Heard Island and Mcdonald Islands', 'HM');
  PERFORM common_create_country (96, true, 'Holy See (Vatican City State)', 'VA');
  PERFORM common_create_country (97, true, 'Honduras', 'HN');
  PERFORM common_create_country (98, true, 'Hong Kong', 'HK');
  PERFORM common_create_country (99, true, 'Hungary', 'HU');
  PERFORM common_create_country (100, true, 'Iceland', 'IS');
  PERFORM common_create_country (101, true, 'India', 'IN');
  PERFORM common_create_country (102, true, 'Indonesia', 'ID');
  PERFORM common_create_country (103, true, 'Iran, Islamic Republic Of', 'IR');
  PERFORM common_create_country (104, true, 'Iraq', 'IQ');
  PERFORM common_create_country (105, true, 'Ireland', 'IE');
  PERFORM common_create_country (106, true, 'Israel', 'IL');
  PERFORM common_create_country (107, true, 'Italy', 'IT');
  PERFORM common_create_country (108, true, 'Jamaica', 'JM');
  PERFORM common_create_country (109, true, 'Japan', 'JP');
  PERFORM common_create_country (110, true, 'Jordan', 'JO');
  PERFORM common_create_country (111, true, 'Kazakhstan', 'KZ');
  PERFORM common_create_country (112, true, 'Kenya', 'KE');
  PERFORM common_create_country (113, true, 'Kiribati', 'KI');
  PERFORM common_create_country (114, true, 'Korea, Democratic Peoples Republic Of', 'KP');
  PERFORM common_create_country (115, true, 'Korea, Republic Of', 'KR');
  PERFORM common_create_country (116, true, 'Kuwait', 'KW');
  PERFORM common_create_country (117, true, 'Kyrgyzstan', 'KG');
  PERFORM common_create_country (118, true, 'Lao Peoples Democratic Republic', 'LA');
  PERFORM common_create_country (119, true, 'Latvia', 'LV');
  PERFORM common_create_country (120, true, 'Lebanon', 'LB');
  PERFORM common_create_country (121, true, 'Lesotho', 'LS');
  PERFORM common_create_country (122, true, 'Liberia', 'LR');
  PERFORM common_create_country (123, true, 'Libyan Arab Jamahiriya', 'LY');
  PERFORM common_create_country (124, true, 'Liechtenstein', 'LI');
  PERFORM common_create_country (125, true, 'Lithuania', 'LT');
  PERFORM common_create_country (126, true, 'Luxembourg', 'LU');
  PERFORM common_create_country (127, true, 'Macao', 'MO');
  PERFORM common_create_country (128, true, 'Macedonia, The Former Yugoslav Republic Of', 'MK');
  PERFORM common_create_country (129, true, 'Madagascar', 'MG');
  PERFORM common_create_country (130, true, 'Malawi', 'MW');
  PERFORM common_create_country (131, true, 'Malaysia', 'MY');
  PERFORM common_create_country (132, true, 'Maldives', 'MV');
  PERFORM common_create_country (133, true, 'Mali', 'ML');
  PERFORM common_create_country (134, true, 'Malta', 'MT');
  PERFORM common_create_country (135, true, 'Marshall Islands', 'MH');
  PERFORM common_create_country (136, true, 'Martinique', 'MQ');
  PERFORM common_create_country (137, true, 'Mauritania', 'MR');
  PERFORM common_create_country (138, true, 'Mauritius', 'MU');
  PERFORM common_create_country (139, true, 'Mayotte', 'YT');
  PERFORM common_create_country (140, true, 'Mexico', 'MX');
  PERFORM common_create_country (141, true, 'Micronesia, Federated States Of', 'FM');
  PERFORM common_create_country (142, true, 'Moldova, Republic Of', 'MD');
  PERFORM common_create_country (143, true, 'Monaco', 'MC');
  PERFORM common_create_country (144, true, 'Mongolia', 'MN');
  PERFORM common_create_country (145, true, 'Montserrat', 'MS');
  PERFORM common_create_country (146, true, 'Morocco', 'MA');
  PERFORM common_create_country (147, true, 'Mozambique', 'MZ');
  PERFORM common_create_country (148, true, 'Myanmar', 'MM');
  PERFORM common_create_country (149, true, 'Namibia', 'NA');
  PERFORM common_create_country (150, true, 'Nauru', 'NR');
  PERFORM common_create_country (151, true, 'Nepal', 'NP');
  PERFORM common_create_country (152, true, 'Netherlands', 'NL');
  PERFORM common_create_country (153, true, 'Netherlands Antilles', 'AN');
  PERFORM common_create_country (154, true, 'New Caledonia', 'NC');
  PERFORM common_create_country (155, true, 'New Zealand', 'NZ');
  PERFORM common_create_country (156, true, 'Nicaragua', 'NI');
  PERFORM common_create_country (157, true, 'Niger', 'NE');
  PERFORM common_create_country (158, true, 'Nigeria', 'NG');
  PERFORM common_create_country (159, true, 'Niue', 'NU');
  PERFORM common_create_country (160, true, 'Norfolk Island', 'NF');
  PERFORM common_create_country (161, true, 'Northern Mariana Islands', 'MP');
  PERFORM common_create_country (162, true, 'Norway', 'NO');
  PERFORM common_create_country (163, true, 'Oman', 'OM');
  PERFORM common_create_country (164, true, 'Pakistan', 'PK');
  PERFORM common_create_country (165, true, 'Palau', 'PW');
  PERFORM common_create_country (166, true, 'Palestinian Territory, Occupied', 'PS');
  PERFORM common_create_country (167, true, 'Panama', 'PA');
  PERFORM common_create_country (168, true, 'Papua New Guinea', 'PG');
  PERFORM common_create_country (169, true, 'Paraguay', 'PY');
  PERFORM common_create_country (170, true, 'Peru', 'PE');
  PERFORM common_create_country (171, true, 'Philippines', 'PH');
  PERFORM common_create_country (172, true, 'Pitcairn', 'PN');
  PERFORM common_create_country (173, true, 'Poland', 'PL');
  PERFORM common_create_country (174, true, 'Portugal', 'PT');
  PERFORM common_create_country (175, true, 'Puerto Rico', 'PR');
  PERFORM common_create_country (176, true, 'Qatar', 'QA');
  PERFORM common_create_country (177, true, 'R Union', 'RE');
  PERFORM common_create_country (178, true, 'Romania', 'RO');
  PERFORM common_create_country (179, true, 'Russian Federation', 'RU');
  PERFORM common_create_country (180, true, 'Rwanda', 'RW');
  PERFORM common_create_country (181, true, 'Saint Helena', 'SH');
  PERFORM common_create_country (182, true, 'Saint Kitts and Nevis', 'KN');
  PERFORM common_create_country (183, true, 'Saint Lucia', 'LC');
  PERFORM common_create_country (184, true, 'Saint Pierre and Miquelon', 'PM');
  PERFORM common_create_country (185, true, 'Saint Vincent and The Grenadines', 'VC');
  PERFORM common_create_country (186, true, 'Samoa', 'WS');
  PERFORM common_create_country (187, true, 'San Marino', 'SM');
  PERFORM common_create_country (188, true, 'Sao Tome and Principe', 'ST');
  PERFORM common_create_country (189, true, 'Saudi Arabia', 'SA');
  PERFORM common_create_country (190, true, 'Senegal', 'SN');
  PERFORM common_create_country (191, true, 'Seychelles', 'SC');
  PERFORM common_create_country (192, true, 'Sierra Leone', 'SL');
  PERFORM common_create_country (193, true, 'Singapore', 'SG');
  PERFORM common_create_country (194, true, 'Slovakia', 'SK');
  PERFORM common_create_country (195, true, 'Slovenia', 'SI');
  PERFORM common_create_country (196, true, 'Solomon Islands', 'SB');
  PERFORM common_create_country (197, true, 'Somalia', 'SO');
  PERFORM common_create_country (198, true, 'South Africa', 'ZA');
  PERFORM common_create_country (199, true, 'South Georgia and The South Sandwich Islands', 'GS');
  PERFORM common_create_country (200, true, 'Spain', 'ES');
  PERFORM common_create_country (201, true, 'Sri Lanka', 'LK');
  PERFORM common_create_country (202, true, 'Sudan', 'SD');
  PERFORM common_create_country (203, true, 'Suriname', 'SR');
  PERFORM common_create_country (204, true, 'Svalbard and Jan Mayen', 'SJ');
  PERFORM common_create_country (205, true, 'Swaziland', 'SZ');
  PERFORM common_create_country (206, true, 'Sweden', 'SE');
  PERFORM common_create_country (207, true, 'Switzerland', 'CH');
  PERFORM common_create_country (208, true, 'Syrian Arab Republic', 'SY');
  PERFORM common_create_country (209, true, 'Taiwan', 'TW');
  PERFORM common_create_country (210, true, 'Tajikistan', 'TJ');
  PERFORM common_create_country (211, true, 'Tanzania, United Republic Of', 'TZ');
  PERFORM common_create_country (212, true, 'Thailand', 'TH');
  PERFORM common_create_country (213, true, 'Togo', 'TG');
  PERFORM common_create_country (214, true, 'Tokelau', 'TK');
  PERFORM common_create_country (215, true, 'Tonga', 'TO');
  PERFORM common_create_country (216, true, 'Trinidad and Tobago', 'TT');
  PERFORM common_create_country (217, true, 'Tunisia', 'TN');
  PERFORM common_create_country (218, true, 'Turkey', 'TR');
  PERFORM common_create_country (219, true, 'Turkmenistan', 'TM');
  PERFORM common_create_country (220, true, 'Turks and Caicos Islands', 'TC');
  PERFORM common_create_country (221, true, 'Tuvalu', 'TV');
  PERFORM common_create_country (222, true, 'Uganda', 'UG');
  PERFORM common_create_country (223, true, 'Ukraine', 'UA');
  PERFORM common_create_country (224, true, 'United Arab Emirates', 'AE');
  PERFORM common_create_country (225, true, 'United Kingdom', 'GB');
  PERFORM common_create_country (226, true, 'United States Minor Outlying Islands', 'UM');
  PERFORM common_create_country (227, true, 'Uruguay', 'UY');
  PERFORM common_create_country (228, true, 'Uzbekistan', 'UZ');
  PERFORM common_create_country (229, true, 'Vanuatu', 'VU');
  PERFORM common_create_country (230, true, 'Venezuela', 'VE');
  PERFORM common_create_country (231, true, 'Viet Nam', 'VN');
  PERFORM common_create_country (232, true, 'Virgin Islands, British', 'VG');
  PERFORM common_create_country (233, true, 'Virgin Islands, U.S.', 'VI');
  PERFORM common_create_country (234, true, 'Wallis and Futuna', 'WF');
  PERFORM common_create_country (235, true, 'Western Sahara', 'EH');
  PERFORM common_create_country (236, true, 'Yemen', 'YE');
  PERFORM common_create_country (237, true, 'Yugoslavia', 'YU');
  PERFORM common_create_country (238, true, 'Zambia', 'ZM');
  PERFORM common_create_country (239, true, 'Zimbabwe', 'ZW');
  PERFORM common_create_country(240,true,'COUNTRY_001','C_001');

success=true;
return success;
END
$$ LANGUAGE plpgsql;