CREATE OR REPLACE FUNCTION test_data_metro_stat_area() --FF NEW
RETURNS boolean AS $$
DECLARE

success BOOLEAN:=FALSE;

BEGIN

  PERFORM common_create_metro_stat_area('MSA_001','MSA_001');
  PERFORM common_create_metro_stat_area('MSA_002','MSA_002');
  PERFORM common_create_metro_stat_area('MSA_003','MSA_003');
  PERFORM common_create_metro_stat_area('MSA_004','MSA_004');

  PERFORM common_create_metro_stat_area('Abilene, TX','Abilene');
  PERFORM common_create_metro_stat_area('Akron, OH','Akron');
  PERFORM common_create_metro_stat_area('Albany, GA','Albany');
  PERFORM common_create_metro_stat_area('Albany-Schenectady-Troy, NY','the Albany Area');
  PERFORM common_create_metro_stat_area('Albuquerque, NM','Albuquerque');
  PERFORM common_create_metro_stat_area('Alexandria, LA','Alexandria');
  PERFORM common_create_metro_stat_area('Allentown-Bethlehem-Easton, PA-NJ','the Allentown Area');
  PERFORM common_create_metro_stat_area('Altoona, PA','Altoona');
  PERFORM common_create_metro_stat_area('Amarillo, TX','Amarillo');
  PERFORM common_create_metro_stat_area('Ames, IA','Ames');
  PERFORM common_create_metro_stat_area('Anchorage, AK','Anchorage');
  PERFORM common_create_metro_stat_area('Anderson, IN','Anderson');
  PERFORM common_create_metro_stat_area('Anderson, SC','Anderson');
  PERFORM common_create_metro_stat_area('Ann Arbor, MI','Ann Arbor');
  PERFORM common_create_metro_stat_area('Anniston-Oxford, AL','the Anniston Area');
  PERFORM common_create_metro_stat_area('Appleton, WI','Appleton');
  PERFORM common_create_metro_stat_area('Asheville, NC','Asheville');
  PERFORM common_create_metro_stat_area('Athens-Clarke County, GA','the Athens Area');
  PERFORM common_create_metro_stat_area('Atlanta-Sandy Springs-Marietta, GA','the Atlanta Area');
  PERFORM common_create_metro_stat_area('Atlantic City-Hammonton, NJ','the Atlantic City Area');
  PERFORM common_create_metro_stat_area('Auburn-Opelika, AL','the Auburn Area');
  PERFORM common_create_metro_stat_area('Augusta-Richmond County, GA-SC','the Augusta Area');
  PERFORM common_create_metro_stat_area('Austin-Round Rock-San Marcos, TX','the Austin Area');
  PERFORM common_create_metro_stat_area('Bakersfield-Delano, CA','the Bakersfield Area');
  PERFORM common_create_metro_stat_area('Baltimore-Towson, MD','the Baltimore Area');
  PERFORM common_create_metro_stat_area('Bangor, ME','Bangor');
  PERFORM common_create_metro_stat_area('Barnstable Town, MA','Barnstable Town');
  PERFORM common_create_metro_stat_area('Baton Rouge, LA','Baton Rouge');
  PERFORM common_create_metro_stat_area('Battle Creek, MI','Battle Creek');
  PERFORM common_create_metro_stat_area('Bay City, MI','Bay City');
  PERFORM common_create_metro_stat_area('Beaumont-Port Arthur, TX','the Beaumont Area');
  PERFORM common_create_metro_stat_area('Bellingham, WA','Bellingham');
  PERFORM common_create_metro_stat_area('Bend, OR','Bend');
  PERFORM common_create_metro_stat_area('Billings, MT','Billings');
  PERFORM common_create_metro_stat_area('Binghamton, NY','Binghamton');
  PERFORM common_create_metro_stat_area('Birmingham-Hoover, AL','the Birmingham Area');
  PERFORM common_create_metro_stat_area('Bismarck, ND','Bismarck');
  PERFORM common_create_metro_stat_area('Blacksburg-Christiansburg-Radford, VA','the Blacksburg Area');
  PERFORM common_create_metro_stat_area('Bloomington, IN','Bloomington');
  PERFORM common_create_metro_stat_area('Bloomington-Normal, IL','the Bloomington Area');
  PERFORM common_create_metro_stat_area('Boise City-Nampa, ID','the Boise City Area');
  PERFORM common_create_metro_stat_area('Boston-Cambridge-Quincy, MA-NH','the Boston Area');
  PERFORM common_create_metro_stat_area('Boulder, CO','Boulder');
  PERFORM common_create_metro_stat_area('Bowling Green, KY','Bowling Green');
  PERFORM common_create_metro_stat_area('Bremerton-Silverdale, WA','the Bremerton Area');
  PERFORM common_create_metro_stat_area('Bridgeport-Stamford-Norwalk, CT','the Stamford Area');
  PERFORM common_create_metro_stat_area('Brownsville-Harlingen, TX','the Brownsville Area');
  PERFORM common_create_metro_stat_area('Brunswick, GA','Brunswick');
  PERFORM common_create_metro_stat_area('Buffalo-Niagara Falls, NY','the Buffalo Area');
  PERFORM common_create_metro_stat_area('Burlington, NC','Burlington');
  PERFORM common_create_metro_stat_area('Burlington-South Burlington, VT','the Burlington Area');
  PERFORM common_create_metro_stat_area('Canton-Massillon, OH','the Canton Area');
  PERFORM common_create_metro_stat_area('Cape Coral-Fort Myers, FL','the Fort Myers Area');
  PERFORM common_create_metro_stat_area('Carson City, NV','Carson City');
  PERFORM common_create_metro_stat_area('Casper, WY','Casper');
  PERFORM common_create_metro_stat_area('Cedar Rapids, IA','Cedar Rapids');
  PERFORM common_create_metro_stat_area('Champaign-Urbana, IL','the Champaign Area');
  PERFORM common_create_metro_stat_area('Charleston, WV','Charleston');
  PERFORM common_create_metro_stat_area('Charleston-North Charleston-Summerville, SC','the Charleston Area');
  PERFORM common_create_metro_stat_area('Charlotte-Gastonia-Rock Hill, NC-SC','the Charlotte Area');
  PERFORM common_create_metro_stat_area('Charlottesville, VA','Charlottesville');
  PERFORM common_create_metro_stat_area('Chattanooga, TN-GA','Chattanooga');
  PERFORM common_create_metro_stat_area('Cheyenne, WY','Cheyenne');
  PERFORM common_create_metro_stat_area('Chicago-Joliet-Naperville, IL-IN-WI','the Chicago Area');
  PERFORM common_create_metro_stat_area('Chico, CA','Chico');
  PERFORM common_create_metro_stat_area('Cincinnati-Middletown, OH-KY-IN','the Cincinnati Area');
  PERFORM common_create_metro_stat_area('Clarksville, TN-KY','Clarksville');
  PERFORM common_create_metro_stat_area('Cleveland, TN','Cleveland');
  PERFORM common_create_metro_stat_area('Cleveland-Elyria-Mentor, OH','the Cleveland Area');
  PERFORM common_create_metro_stat_area('Coeur d''Alene, ID','Coeur d''Alene');
  PERFORM common_create_metro_stat_area('College Station-Bryan, TX','the College Station Area');
  PERFORM common_create_metro_stat_area('Colorado Springs, CO','Colorado Springs');
  PERFORM common_create_metro_stat_area('Columbia, MO','Columbia');
  PERFORM common_create_metro_stat_area('Columbia, SC','Columbia');
  PERFORM common_create_metro_stat_area('Columbus, GA-AL','Columbus');
  PERFORM common_create_metro_stat_area('Columbus, IN','Columbus');
  PERFORM common_create_metro_stat_area('Columbus, OH','Columbus');
  PERFORM common_create_metro_stat_area('Corpus Christi, TX','Corpus Christi');
  PERFORM common_create_metro_stat_area('Corvallis, OR','Corvallis');
  PERFORM common_create_metro_stat_area('Cumberland, MD-WV','Cumberland');
  PERFORM common_create_metro_stat_area('Dallas-Fort Worth-Arlington, TX','the Dallas Area');
  PERFORM common_create_metro_stat_area('Dalton, GA','Dalton');
  PERFORM common_create_metro_stat_area('Danville, IL','Danville');
  PERFORM common_create_metro_stat_area('Danville, VA','Danville');
  PERFORM common_create_metro_stat_area('Davenport-Moline-Rock Island, IA-IL','the Davenport Area');
  PERFORM common_create_metro_stat_area('Dayton, OH','Dayton');
  PERFORM common_create_metro_stat_area('Decatur, AL','Decatur');
  PERFORM common_create_metro_stat_area('Decatur, IL','Decatur');
  PERFORM common_create_metro_stat_area('Deltona-Daytona Beach-Ormond Beach, FL','the Daytona Beach Area');
  PERFORM common_create_metro_stat_area('Denver-Aurora-Broomfield, CO','the Denver Area');
  PERFORM common_create_metro_stat_area('Des Moines-West Des Moines, IA','the Des Moines Area');
  PERFORM common_create_metro_stat_area('Detroit-Warren-Livonia, MI','the Detroit Area');
  PERFORM common_create_metro_stat_area('Dothan, AL','Dothan');
  PERFORM common_create_metro_stat_area('Dover, DE','Dover');
  PERFORM common_create_metro_stat_area('Dubuque, IA','Dubuque');
  PERFORM common_create_metro_stat_area('Duluth, MN-WI','Duluth');
  PERFORM common_create_metro_stat_area('Durham-Chapel Hill, NC','Durham');
  PERFORM common_create_metro_stat_area('Eau Claire, WI','Eau Claire');
  PERFORM common_create_metro_stat_area('El Centro, CA','El Centro');
  PERFORM common_create_metro_stat_area('Elizabethtown, KY','Elizabethtown');
  PERFORM common_create_metro_stat_area('Elkhart-Goshen, IN','the Elkhart Area');
  PERFORM common_create_metro_stat_area('Elmira, NY','Elmira');
  PERFORM common_create_metro_stat_area('El Paso, TX','El Paso');
  PERFORM common_create_metro_stat_area('Erie, PA','Erie');
  PERFORM common_create_metro_stat_area('Eugene-Springfield, OR','the Eugene Area');
  PERFORM common_create_metro_stat_area('Evansville, IN-KY','Evansville');
  PERFORM common_create_metro_stat_area('Fairbanks, AK','Fairbanks');
  PERFORM common_create_metro_stat_area('Fargo, ND-MN','Fargo');
  PERFORM common_create_metro_stat_area('Farmington, NM','Farmington');
  PERFORM common_create_metro_stat_area('Fayetteville, NC','Fayetteville');
  PERFORM common_create_metro_stat_area('Fayetteville-Springdale-Rogers, AR-MO','the Fayetteville Area');
  PERFORM common_create_metro_stat_area('Flagstaff, AZ','Flagstaff');
  PERFORM common_create_metro_stat_area('Flint, MI','Flint');
  PERFORM common_create_metro_stat_area('Florence, SC','Florence');
  PERFORM common_create_metro_stat_area('Florence-Muscle Shoals, AL','the Florence Area');
  PERFORM common_create_metro_stat_area('Fond du Lac, WI','Fond du Lac');
  PERFORM common_create_metro_stat_area('Fort Collins-Loveland, CO','the Fort Collins Area');
  PERFORM common_create_metro_stat_area('Fort Smith, AR-OK','Fort Smith');
  PERFORM common_create_metro_stat_area('Crestview-Fort Walton Beach-Destin, FL','the Fort Walton Beach Area');
  PERFORM common_create_metro_stat_area('Fort Wayne, IN','Fort Wayne');
  PERFORM common_create_metro_stat_area('Fresno, CA','Fresno');
  PERFORM common_create_metro_stat_area('Gadsden, AL','Gadsden');
  PERFORM common_create_metro_stat_area('Gainesville, FL','Gainesville');
  PERFORM common_create_metro_stat_area('Gainesville, GA','Gainesville');
  PERFORM common_create_metro_stat_area('Glens Falls, NY','Glens Falls');
  PERFORM common_create_metro_stat_area('Goldsboro, NC','Goldsboro');
  PERFORM common_create_metro_stat_area('Grand Forks, ND-MN','Grand Forks');
  PERFORM common_create_metro_stat_area('Grand Junction, CO','Grand Junction');
  PERFORM common_create_metro_stat_area('Grand Rapids-Wyoming, MI','the Grand Rapids Area');
  PERFORM common_create_metro_stat_area('Great Falls, MT','Great Falls');
  PERFORM common_create_metro_stat_area('Greeley, CO','Greeley');
  PERFORM common_create_metro_stat_area('Green Bay, WI','Green Bay');
  PERFORM common_create_metro_stat_area('Greensboro-High Point, NC','the Greensboro Area');
  PERFORM common_create_metro_stat_area('Greenville, NC','Greenville');
  PERFORM common_create_metro_stat_area('Greenville-Mauldin-Easley, SC','Greenville');
  PERFORM common_create_metro_stat_area('Gulfport-Biloxi, MS','the Gulfport Area');
  PERFORM common_create_metro_stat_area('Hagerstown-Martinsburg, MD-WV','the Hagerstown Area');
  PERFORM common_create_metro_stat_area('Hanford-Corcoran, CA','the Hanford Area');
  PERFORM common_create_metro_stat_area('Harrisburg-Carlisle, PA','the Harrisburg Area');
  PERFORM common_create_metro_stat_area('Harrisonburg, VA','Harrisonburg');
  PERFORM common_create_metro_stat_area('Hartford-West Hartford-East Hartford, CT','the Hartford Area');
  PERFORM common_create_metro_stat_area('Hattiesburg, MS','Hattiesburg');
  PERFORM common_create_metro_stat_area('Hickory-Lenoir-Morganton, NC','the Hickory Area');
  PERFORM common_create_metro_stat_area('Hinesville-Fort Stewart, GA','the Hinesville Area');
  PERFORM common_create_metro_stat_area('Holland-Grand Haven, MI','the Holland Area');
  PERFORM common_create_metro_stat_area('Honolulu, HI','Honolulu');
  PERFORM common_create_metro_stat_area('Hot Springs, AR','Hot Springs');
  PERFORM common_create_metro_stat_area('Houma-Bayou Cane-Thibodaux, LA','the Houma Area');
  PERFORM common_create_metro_stat_area('Houston-Sugar Land-Baytown, TX','the Houston Area');
  PERFORM common_create_metro_stat_area('Huntington-Ashland, WV-KY-OH','the Huntington Area');
  PERFORM common_create_metro_stat_area('Huntsville, AL','Huntsville');
  PERFORM common_create_metro_stat_area('Idaho Falls, ID','Idaho Falls');
  PERFORM common_create_metro_stat_area('Indianapolis-Carmel, IN','the Indianapolis Area');
  PERFORM common_create_metro_stat_area('Iowa City, IA','Iowa City');
  PERFORM common_create_metro_stat_area('Ithaca, NY','Ithaca');
  PERFORM common_create_metro_stat_area('Jackson, MI','Jackson');
  PERFORM common_create_metro_stat_area('Jackson, MS','Jackson');
  PERFORM common_create_metro_stat_area('Jackson, TN','Jackson');
  PERFORM common_create_metro_stat_area('Jacksonville, FL','Jacksonville');
  PERFORM common_create_metro_stat_area('Jacksonville, NC','Jacksonville');
  PERFORM common_create_metro_stat_area('Janesville, WI','Janesville');
  PERFORM common_create_metro_stat_area('Jefferson City, MO','Jefferson City');
  PERFORM common_create_metro_stat_area('Johnson City, TN','Johnson City');
  PERFORM common_create_metro_stat_area('Johnstown, PA','Johnstown');
  PERFORM common_create_metro_stat_area('Jonesboro, AR','Jonesboro');
  PERFORM common_create_metro_stat_area('Joplin, MO','Joplin');
  PERFORM common_create_metro_stat_area('Kalamazoo-Portage, MI','the Kalamazoo Area');
  PERFORM common_create_metro_stat_area('Kankakee-Bradley, IL','the Kankakee Area');
  PERFORM common_create_metro_stat_area('Kansas City, MO-KS','Kansas City');
  PERFORM common_create_metro_stat_area('Kennewick-Pasco-Richland, WA','the Kennewick Area');
  PERFORM common_create_metro_stat_area('Killeen-Temple-Fort Hood, TX','the Killeen Area');
  PERFORM common_create_metro_stat_area('Kingsport-Bristol-Bristol, TN-VA','the Kingsport Area');
  PERFORM common_create_metro_stat_area('Kingston, NY','Kingston');
  PERFORM common_create_metro_stat_area('Knoxville, TN','Knoxville');
  PERFORM common_create_metro_stat_area('Kokomo, IN','Kokomo');
  PERFORM common_create_metro_stat_area('La Crosse, WI-MN','La Crosse');
  PERFORM common_create_metro_stat_area('Lafayette, IN','Lafayette');
  PERFORM common_create_metro_stat_area('Lafayette, LA','Lafayette');
  PERFORM common_create_metro_stat_area('Lake Charles, LA','Lake Charles');
  PERFORM common_create_metro_stat_area('Lakeland-Winter Haven, FL','the Lakeland Area');
  PERFORM common_create_metro_stat_area('Lancaster, PA','Lancaster');
  PERFORM common_create_metro_stat_area('Lansing-East Lansing, MI','the Lansing Area');
  PERFORM common_create_metro_stat_area('Laredo, TX','Laredo');
  PERFORM common_create_metro_stat_area('Las Cruces, NM','Las Cruces');
  PERFORM common_create_metro_stat_area('Las Vegas-Paradise, NV','the Las Vegas Area');
  PERFORM common_create_metro_stat_area('Lawrence, KS','Lawrence');
  PERFORM common_create_metro_stat_area('Lawton, OK','Lawton');
  PERFORM common_create_metro_stat_area('Lebanon, PA','Lebanon');
  PERFORM common_create_metro_stat_area('Lewiston, ID-WA','Lewiston');
  PERFORM common_create_metro_stat_area('Lewiston-Auburn, ME','the Lewiston Area');
  PERFORM common_create_metro_stat_area('Lexington-Fayette, KY','the Lexington Area');
  PERFORM common_create_metro_stat_area('Lima, OH','Lima');
  PERFORM common_create_metro_stat_area('Lincoln, NE','Lincoln');
  PERFORM common_create_metro_stat_area('Little Rock-North Little Rock-Conway, AR','the Little Rock Area');
  PERFORM common_create_metro_stat_area('Logan, UT-ID','Logan');
  PERFORM common_create_metro_stat_area('Longview, TX','Longview');
  PERFORM common_create_metro_stat_area('Longview, WA','Longview');
  PERFORM common_create_metro_stat_area('Los Angeles-Long Beach-Santa Ana, CA','the Los Angeles Area');
  PERFORM common_create_metro_stat_area('Louisville-Jefferson County, KY-IN','the Louisville Area');
  PERFORM common_create_metro_stat_area('Lubbock, TX','Lubbock');
  PERFORM common_create_metro_stat_area('Lynchburg, VA','Lynchburg');
  PERFORM common_create_metro_stat_area('Macon, GA','Macon');
  PERFORM common_create_metro_stat_area('Madera-Chowchilla, CA','Madera');
  PERFORM common_create_metro_stat_area('Madison, WI','Madison');
  PERFORM common_create_metro_stat_area('Manchester-Nashua, NH','the Manchester Area');
  PERFORM common_create_metro_stat_area('Mansfield, OH','Mansfield');
  PERFORM common_create_metro_stat_area('McAllen-Edinburg-Mission, TX','the McAllen Area');
  PERFORM common_create_metro_stat_area('Medford, OR','Medford');
  PERFORM common_create_metro_stat_area('Memphis, TN-MS-AR','Memphis');
  PERFORM common_create_metro_stat_area('Merced, CA','Merced');
  PERFORM common_create_metro_stat_area('Miami-Fort Lauderdale-Pompano Beach, FL','the Miami Area');
  PERFORM common_create_metro_stat_area('Michigan City-La Porte, IN','the Michigan City Area');
  PERFORM common_create_metro_stat_area('Midland, TX','Midland');
  PERFORM common_create_metro_stat_area('Milwaukee-Waukesha-West Allis, WI','the Milwaukee Area');
  PERFORM common_create_metro_stat_area('Minneapolis-St. Paul-Bloomington, MN-WI','the Minneapolis Area');
  PERFORM common_create_metro_stat_area('Missoula, MT','Missoula');
  PERFORM common_create_metro_stat_area('Mobile, AL','Mobile');
  PERFORM common_create_metro_stat_area('Modesto, CA','Modesto');
  PERFORM common_create_metro_stat_area('Monroe, LA','Monroe');
  PERFORM common_create_metro_stat_area('Monroe, MI','Monroe');
  PERFORM common_create_metro_stat_area('Montgomery, AL','Montgomery');
  PERFORM common_create_metro_stat_area('Morgantown, WV','Morgantown');
  PERFORM common_create_metro_stat_area('Morristown, TN','Morristown');
  PERFORM common_create_metro_stat_area('Mount Vernon-Anacortes, WA','the Mount Vernon Area');
  PERFORM common_create_metro_stat_area('Muncie, IN','Muncie');
  PERFORM common_create_metro_stat_area('Muskegon-Norton Shores, MI','the Muskegon Area');
  PERFORM common_create_metro_stat_area('Myrtle Beach-North Myrtle Beach-Conway, SC','the Myrtle Beach Area');
  PERFORM common_create_metro_stat_area('Napa, CA','Napa');
  PERFORM common_create_metro_stat_area('Naples-Marco Island, FL','the Naples Area');
  PERFORM common_create_metro_stat_area('Nashville-Davidson-Murfreesboro-Franklin, TN','the Nashville Area');
  PERFORM common_create_metro_stat_area('New Haven-Milford, CT','the New Haven Area');
  PERFORM common_create_metro_stat_area('New Orleans-Metairie-Kenner, LA','the New Orleans Area');
  PERFORM common_create_metro_stat_area('New York-Northern New Jersey-Long Island, NY-NJ-PA','the New York City Area');
  PERFORM common_create_metro_stat_area('Niles-Benton Harbor, MI','the Niles Area');
  PERFORM common_create_metro_stat_area('Norwich-New London, CT','the Norwich Area');
  PERFORM common_create_metro_stat_area('Ocala, FL','Ocala');
  PERFORM common_create_metro_stat_area('Ocean City, NJ','Ocean City');
  PERFORM common_create_metro_stat_area('Odessa, TX','Odessa');
  PERFORM common_create_metro_stat_area('Ogden-Clearfield, UT','the Ogden Area');
  PERFORM common_create_metro_stat_area('Oklahoma City, OK','Oklahoma City');
  PERFORM common_create_metro_stat_area('Olympia, WA','Olympia');
  PERFORM common_create_metro_stat_area('Omaha-Council Bluffs, NE-IA','the Omaha Area');
  PERFORM common_create_metro_stat_area('Orlando-Kissimmee-Sanford, FL','the Orlando Area');
  PERFORM common_create_metro_stat_area('Oshkosh-Neenah, WI','Oshkosh');
  PERFORM common_create_metro_stat_area('Owensboro, KY','Owensboro');
  PERFORM common_create_metro_stat_area('Oxnard-Thousand Oaks-Ventura, CA','the Oxnard Area');
  PERFORM common_create_metro_stat_area('Palm Bay-Melbourne-Titusville, FL','the Palm Bay Area');
  PERFORM common_create_metro_stat_area('Panama City-Lynn Haven-Panama City Beach, FL','the Panama City Area');
  PERFORM common_create_metro_stat_area('Parkersburg-Marietta-Vienna, WV-OH','the Parkersburg Area');
  PERFORM common_create_metro_stat_area('Pascagoula, MS','Pascagoula');
  PERFORM common_create_metro_stat_area('Pensacola-Ferry Pass-Brent, FL','the Pensacola Area');
  PERFORM common_create_metro_stat_area('Peoria, IL','Peoria');
  PERFORM common_create_metro_stat_area('Philadelphia-Camden-Wilmington, PA-NJ-DE-MD','the Philadelphia Area');
  PERFORM common_create_metro_stat_area('Phoenix-Mesa-Glendale, AZ','the Phoenix Area');
  PERFORM common_create_metro_stat_area('Pine Bluff, AR','Pine Bluff');
  PERFORM common_create_metro_stat_area('Pittsburgh, PA','Pittsburgh');
  PERFORM common_create_metro_stat_area('Pittsfield, MA','Pittsfield');
  PERFORM common_create_metro_stat_area('Pocatello, ID','Pocatello');
  PERFORM common_create_metro_stat_area('Portland-South Portland-Biddeford, ME','the Portland Area');
  PERFORM common_create_metro_stat_area('Portland-Vancouver-Hillsboro, OR-WA','the Portland Area');
  PERFORM common_create_metro_stat_area('Port St. Lucie, FL','the Port St. Lucie Area');
  PERFORM common_create_metro_stat_area('Poughkeepsie-Newburgh-Middletown, NY','the Poughkeepsie Area');
  PERFORM common_create_metro_stat_area('Prescott, AZ','Prescott');
  PERFORM common_create_metro_stat_area('Providence-New Bedford-Fall River, RI-MA','the Providence Area');
  PERFORM common_create_metro_stat_area('Provo-Orem, UT','the Provo Area');
  PERFORM common_create_metro_stat_area('Pueblo, CO','Pueblo');
  PERFORM common_create_metro_stat_area('Punta Gorda, FL','Punta Gorda');
  PERFORM common_create_metro_stat_area('Racine, WI','Racine');
  PERFORM common_create_metro_stat_area('Raleigh-Cary, NC','the Raleigh Area');
  PERFORM common_create_metro_stat_area('Rapid City, SD','Rapid City');
  PERFORM common_create_metro_stat_area('Reading, PA','Reading');
  PERFORM common_create_metro_stat_area('Redding, CA','Redding');
  PERFORM common_create_metro_stat_area('Reno-Sparks, NV','the Reno Area');
  PERFORM common_create_metro_stat_area('Richmond, VA','Richmond');
  PERFORM common_create_metro_stat_area('Riverside-San Bernardino-Ontario, CA','the Riverside Area');
  PERFORM common_create_metro_stat_area('Roanoke, VA','Roanoke');
  PERFORM common_create_metro_stat_area('Rochester, MN','Rochester');
  PERFORM common_create_metro_stat_area('Rochester, NY','Rochester');
  PERFORM common_create_metro_stat_area('Rockford, IL','Rockford');
  PERFORM common_create_metro_stat_area('Rocky Mount, NC','Rocky Mount');
  PERFORM common_create_metro_stat_area('Rome, GA','Rome');
  PERFORM common_create_metro_stat_area('Sacramento--Arden-Arcade--Roseville, CA','the Sacramento Area');
  PERFORM common_create_metro_stat_area('Saginaw-Saginaw Township North, MI','the Saginaw Area');
  PERFORM common_create_metro_stat_area('St. Cloud, MN','St. Cloud');
  PERFORM common_create_metro_stat_area('St. George, UT','St. George');
  PERFORM common_create_metro_stat_area('St. Joseph, MO-KS','St. Joseph');
  PERFORM common_create_metro_stat_area('St. Louis, MO-IL','St. Louis');
  PERFORM common_create_metro_stat_area('Salem, OR','Salem');
  PERFORM common_create_metro_stat_area('Salinas, CA','Salinas');
  PERFORM common_create_metro_stat_area('Salisbury, MD','Salisbury');
  PERFORM common_create_metro_stat_area('Salt Lake City, UT','Salt Lake City');
  PERFORM common_create_metro_stat_area('San Angelo, TX','San Angelo');
  PERFORM common_create_metro_stat_area('San Antonio-New Braunfels, TX','San Antonio');
  PERFORM common_create_metro_stat_area('San Diego-Carlsbad-San Marcos, CA','the San Diego Area');
  PERFORM common_create_metro_stat_area('Sandusky, OH','Sandusky');
  PERFORM common_create_metro_stat_area('San Francisco-Oakland-Fremont, CA','the San Francisco Area');
  PERFORM common_create_metro_stat_area('San Jose-Sunnyvale-Santa Clara, CA','the San Jose Area');
  PERFORM common_create_metro_stat_area('San Luis Obispo-Paso Robles, CA','the San Luis Obispo Area');
  PERFORM common_create_metro_stat_area('Santa Barbara-Santa Maria-Goleta, CA','the Santa Barbara Area');
  PERFORM common_create_metro_stat_area('Santa Cruz-Watsonville, CA','the Santa Cruz Area');
  PERFORM common_create_metro_stat_area('Santa Fe, NM','Santa Fe');
  PERFORM common_create_metro_stat_area('Santa Rosa-Petaluma, CA','the Santa Rosa Area');
  PERFORM common_create_metro_stat_area('North Port-Bradenton-Sarasota, FL','the Sarasota Area');
  PERFORM common_create_metro_stat_area('Savannah, GA','Savannah');
  PERFORM common_create_metro_stat_area('Scranton--Wilkes-Barre, PA','the Scranton Area');
  PERFORM common_create_metro_stat_area('Seattle-Tacoma-Bellevue, WA','the Seattle Area');
  PERFORM common_create_metro_stat_area('Sebastian-Vero Beach, FL','the Sebastian Area');
  PERFORM common_create_metro_stat_area('Sheboygan, WI','Sheboygan');
  PERFORM common_create_metro_stat_area('Sherman-Denison, TX','the Sherman Area');
  PERFORM common_create_metro_stat_area('Shreveport-Bossier City, LA','the Shreveport Area');
  PERFORM common_create_metro_stat_area('Sioux City, IA-NE-SD','Sioux City');
  PERFORM common_create_metro_stat_area('Sioux Falls, SD','Sioux Falls');
  PERFORM common_create_metro_stat_area('South Bend-Mishawaka, IN-MI','the South Bend Area');
  PERFORM common_create_metro_stat_area('Spartanburg, SC','Spartanburg');
  PERFORM common_create_metro_stat_area('Spokane, WA','Spokane');
  PERFORM common_create_metro_stat_area('Springfield, IL','Springfield');
  PERFORM common_create_metro_stat_area('Springfield, MA','Springfield');
  PERFORM common_create_metro_stat_area('Springfield, MO','Springfield');
  PERFORM common_create_metro_stat_area('Springfield, OH','Springfield');
  PERFORM common_create_metro_stat_area('State College, PA','State College');
  PERFORM common_create_metro_stat_area('Stockton, CA','Stockton');
  PERFORM common_create_metro_stat_area('Sumter, SC','Sumter');
  PERFORM common_create_metro_stat_area('Syracuse, NY','Syracuse');
  PERFORM common_create_metro_stat_area('Tallahassee, FL','Tallahassee');
  PERFORM common_create_metro_stat_area('Tampa-St. Petersburg-Clearwater, FL','the Tampa Area');
  PERFORM common_create_metro_stat_area('Terre Haute, IN','Terre Haute');
  PERFORM common_create_metro_stat_area('Texarkana, TX-Texarkana, AR','Texarkana');
  PERFORM common_create_metro_stat_area('Toledo, OH','Toledo');
  PERFORM common_create_metro_stat_area('Topeka, KS','Topeka');
  PERFORM common_create_metro_stat_area('Trenton-Ewing, NJ','the Trenton Area');
  PERFORM common_create_metro_stat_area('Tucson, AZ','Tucson');
  PERFORM common_create_metro_stat_area('Tulsa, OK','Tulsa');
  PERFORM common_create_metro_stat_area('Tuscaloosa, AL','Tuscaloosa');
  PERFORM common_create_metro_stat_area('Tyler, TX','Tyler');
  PERFORM common_create_metro_stat_area('Utica-Rome, NY','the Utica Area');
  PERFORM common_create_metro_stat_area('Valdosta, GA','Valdosta');
  PERFORM common_create_metro_stat_area('Vallejo-Fairfield, CA','the Vallejo Area');
  PERFORM common_create_metro_stat_area('Victoria, TX','Victoria');
  PERFORM common_create_metro_stat_area('Vineland-Millville-Bridgeton, NJ','the Vineland Area');
  PERFORM common_create_metro_stat_area('Virginia Beach-Norfolk-Newport News, VA-NC','the Virginia Beach Area');
  PERFORM common_create_metro_stat_area('Visalia-Porterville, CA','the Visalia Area');
  PERFORM common_create_metro_stat_area('Waco, TX','Waco');
  PERFORM common_create_metro_stat_area('Warner Robins, GA','Warner Robins');
  PERFORM common_create_metro_stat_area('Washington-Arlington-Alexandria, DC-VA-MD-WV','the Washington Area');
  PERFORM common_create_metro_stat_area('Waterloo-Cedar Falls, IA','the Waterloo Area');
  PERFORM common_create_metro_stat_area('Wausau, WI','Wausau');
  PERFORM common_create_metro_stat_area('Steubenville-Weirton, OH-WV','the Weirton Area');
  PERFORM common_create_metro_stat_area('Wenatchee, WA','Wenatchee');
  PERFORM common_create_metro_stat_area('Wheeling, WV-OH','Wheeling');
  PERFORM common_create_metro_stat_area('Wichita, KS','Wichita');
  PERFORM common_create_metro_stat_area('Wichita Falls, TX','Wichita Falls');
  PERFORM common_create_metro_stat_area('Williamsport, PA','Williamsport');
  PERFORM common_create_metro_stat_area('Wilmington, NC','Wilmington');
  PERFORM common_create_metro_stat_area('Winchester, VA-WV','Winchester');
  PERFORM common_create_metro_stat_area('Winston-Salem, NC','the Winston Area');
  PERFORM common_create_metro_stat_area('Worcester, MA','Worcester');
  PERFORM common_create_metro_stat_area('Yakima, WA','Yakima');
  PERFORM common_create_metro_stat_area('York-Hanover, PA','the York Area');
  PERFORM common_create_metro_stat_area('Youngstown-Warren-Boardman, OH-PA','the Youngstown Area');
  PERFORM common_create_metro_stat_area('Yuba City, CA','Yuba City');
  PERFORM common_create_metro_stat_area('Yuma, AZ','Yuma');
  PERFORM common_create_metro_stat_area('Aguadilla-Isabela-San Sebastian, PR','the Aguadilla Area');
  PERFORM common_create_metro_stat_area('Fajardo, PR','Fajardo');
  PERFORM common_create_metro_stat_area('Guayama, PR','Guayama');
  PERFORM common_create_metro_stat_area('Mayaguez, PR','Mayaguez');
  PERFORM common_create_metro_stat_area('Ponce, PR','Ponce');
  PERFORM common_create_metro_stat_area('San German-Cabo Rojo, PR','the San German Area');
  PERFORM common_create_metro_stat_area('San Juan-Caguas-Guaynabo, PR','the San Juan Area');
  PERFORM common_create_metro_stat_area('Yauco, PR','Yauco');
  PERFORM common_create_metro_stat_area('Cape Girardeau-Jackson, MO-IL','the Cape Girardeau Area');
  PERFORM common_create_metro_stat_area('Lake Havasu City-Kingman, AZ','the Lake Havasu City Area');
  PERFORM common_create_metro_stat_area('Manhattan, KS','Manhattan');
  PERFORM common_create_metro_stat_area('Mankato-North Mankato, MN','the Mankato Area');
  PERFORM common_create_metro_stat_area('Palm Coast, FL','Palm Coast');



success=true;
return success;
END
$$ LANGUAGE plpgsql;