-- Run from root of project
-- psql -d sandbox_ff_new -h restrictions20-psql94.cayadjd1xwwj.us-east-1.rds.amazonaws.com -U postgres -W < Load/load_ff_new.sql
-- VsOCWIozIelwQcRgR4w3

--psql -d sandbox_ff_new -h localhost -U postgres -W < Load/load_ff_new.sql

-- Common
\i 'Common/call_functions_from_table.sql'
\i 'Common/common_create_test_data_functions.sql'
\i 'Common/common_get_table_id_by_name.sql'

-- Fingertip Common
\i 'Common/fingertip/create_sequences.sql'
\i 'Common/fingertip/clear_test_data.sql'
\i 'Common/fingertip/common_create_benefit_structure.sql'
\i 'Common/fingertip/common_create_benefit_structure_copay.sql'
\i 'Common/fingertip/common_create_benefit_structure_copay_value.sql'
\i 'Common/fingertip/common_create_benefit_structure_state.sql'
\i 'Common/fingertip/common_create_corporate_structure.sql'
\i 'Common/fingertip/common_create_country.sql'
\i 'Common/fingertip/common_create_county.sql'
\i 'Common/fingertip/common_create_drug.sql'
\i 'Common/fingertip/common_create_drug_class.sql'
\i 'Common/fingertip/common_create_drug_drug_class.sql'
\i 'Common/fingertip/common_create_drug_jcode.sql'
\i 'Common/fingertip/common_create_formulary.sql'
\i 'Common/fingertip/common_create_formulary_entry.sql'
\i 'Common/fingertip/common_create_formulary_entry_qualifier.sql'
\i 'Common/fingertip/common_create_health_plan.sql'
\i 'Common/fingertip/common_create_health_plan_county.sql'
\i 'Common/fingertip/common_create_health_plan_county_lives.sql'
\i 'Common/fingertip/common_create_health_plan_state.sql'
\i 'Common/fingertip/common_create_health_plan_type.sql'
\i 'Common/fingertip/common_create_hli_medical_benefit_lives.sql'
\i 'Common/fingertip/common_create_jcode.sql'
\i 'Common/fingertip/common_create_metro_stat_area.sql'
\i 'Common/fingertip/common_create_mv_active_formulary.sql'
\i 'Common/fingertip/common_create_parent.sql'
\i 'Common/fingertip/common_create_provider.sql'
\i 'Common/fingertip/common_create_qualifier.sql'
\i 'Common/fingertip/common_create_reason_codes.sql'
\i 'Common/fingertip/common_create_state.sql'
\i 'Common/fingertip/common_create_tier.sql'
\i 'Common/fingertip/common_get_county_id_by_name_and_state.sql'
\i 'Common/fingertip/common_get_formulary_id_by_plan_name.sql'
\i 'Common/fingertip/common_get_reason_code_id_by_code.sql'
\i 'Common/fingertip/common_create_hli_medical_benefit_designs.sql'


\i 'Common/fingertip/common_insert_test_data_functions_table.sql'
\i 'Common/fingertip/test_data_counties.sql'
\i 'Common/fingertip/test_data_country.sql'
\i 'Common/fingertip/test_data_drug_classes.sql'
\i 'Common/fingertip/test_data_drug_drug_classes.sql'
\i 'Common/fingertip/test_data_drug_jcodes.sql'
\i 'Common/fingertip/test_data_drugs.sql'
\i 'Common/fingertip/test_data_formulary_entry.sql'
\i 'Common/fingertip/test_data_health_plan_copay.sql'
\i 'Common/fingertip/test_data_health_plan_counties.sql'
\i 'Common/fingertip/test_data_health_plan_county_lives.sql'
\i 'Common/fingertip/test_data_health_plan_state.sql'
\i 'Common/fingertip/test_data_health_plan_types.sql'
\i 'Common/fingertip/test_data_health_plans.sql'
\i 'Common/fingertip/test_data_hli_medical_benefit_lives.sql'
\i 'Common/fingertip/test_data_jcodes.sql'
\i 'Common/fingertip/test_data_metro_stat_area.sql'
\i 'Common/fingertip/test_data_parent.sql'
\i 'Common/fingertip/test_data_provider.sql'
\i 'Common/fingertip/test_data_qualifiers.sql'
\i 'Common/fingertip/test_data_reason_codes.sql'
\i 'Common/fingertip/test_data_states.sql'
\i 'Common/fingertip/test_data_tiers.sql'
\i 'Common/fingertip/test_data_hli_medical_benefit_designs.sql'
\i 'Common/fingertip/throw_error.sql'

