CREATE OR REPLACE FUNCTION switch_db_names(data_warehouse_db_name varchar, FRONT_END_DB_NAME varchar, REPORT_DATA_DB_NAME varchar, ADMIN_DB_NAME varchar, DATA_ENTRY_DB_NAME varchar, FF_NEW_DB_NAME varchar)
RETURNS void AS $$
DECLARE
  
BEGIN

  ALTER DATABASE $TEMP_DATAWAREHOUSE_DB_NAME RENAME TO $DATAWAREHOUSE_DB_NAME;
  ALTER DATABASE $TEMP_FRONT_END_DB_NAME RENAME TO $FRONT_END_DB_NAME;
  ALTER DATABASE $TEMP_REPORT_DATA_DB_NAME RENAME TO $REPORT_DATA_DB_NAME;
  ALTER DATABASE $TEMP_ADMIN_DB_NAME RENAME TO $ADMIN_DB_NAME;
  ALTER DATABASE $TEMP_DATA_ENTRY_DB_NAME RENAME TO $DATA_ENTRY_DB_NAME;
  ALTER DATABASE $TEMP_FF_NEW_DB_NAME RENAME TO $FF_NEW_DB_NAME;

END
$$ LANGUAGE plpgsql;
