CREATE OR REPLACE FUNCTION validate_drugs_data()-- DATA WAREHOUSE
RETURNS BOOLEAN AS $$
DECLARE
SUCCESS BOOLEAN DEFAULT FALSE;
FF_DRUGS_COUNT INTEGER;-- FF SOURCE DATA DRUGS COUNT
FE_DRUGS_COUNT INTEGER;-- FE SCHEMA DRUGS COUNT 
DW_FF_DRUGS_COUNT INTEGER;-- DRUGS MATERIALIZED VIEW COUNT 
FF_FE_MERGED_DRUGS_COUNT INTEGER;-- FE AND FF SOURCE DATA MERGED DRUGS COUNT
FF_DW_MERGED_DRUGS_COUNT INTEGER;-- DRUGS MATERIALIZED VIEW AND FF SOURCE DATA MERGED COUNT
BEGIN
--COUNT DRUGS IN FF SOURCE DATABASE
SELECT COUNT(*) INTO FF_DRUGS_COUNT FROM ff.drugs_import  ffd WHERE ffd.is_active=TRUE;

--COUNT DRUGS PLANS IN FE SCHEMA
SELECT COUNT(*) INTO FE_DRUGS_COUNT FROM fe.drugs fed;

--COUNT DRUGS IN DW MATERIALIZED VIEW
SELECT COUNT(*) INTO DW_FF_DRUGS_COUNT FROM ff.drugs d;

--IF FE SCHEMA AND FF SOURCE DATA HAVE EQUAL COUNTS
IF FF_DRUGS_COUNT = FE_DRUGS_COUNT THEN
	SELECT COUNT(*) INTO FF_FE_MERGED_DRUGS_COUNT FROM ff.drugs_import ffd JOIN fe.drugs fed ON ffd.id=fed.id AND ffd.is_active=TRUE AND ffd.is_active=fed.is_active AND ffd.name=fed.name;
	--VALIDATE IF FF SOURCE DATA AND FE SCHEMAS HAVE THE SAME RECORDS
	IF FF_DRUGS_COUNT = FF_FE_MERGED_DRUGS_COUNT THEN
		SUCCESS :=TRUE;
	ELSE
		select throw_error('FF AND FE SCHEMAS CONTAINS DIFFERENT DRUGS');
		SUCCESS:=FALSE; 	
	END IF;
ELSE
		select throw_error('FF AND FE SCHEMAS CONTAINS DIFFERENT DRUGS');
		SUCCESS:=FALSE; 
END IF;

--IF FF SOURCE DATA AND DRUGS MATERIALIZED VIEW HAVE EQUAL COUNTS
IF FF_DRUGS_COUNT = DW_FF_DRUGS_COUNT THEN
	SELECT COUNT(*) INTO FF_DW_MERGED_DRUGS_COUNT FROM ff.drugs_import ffd JOIN ff.drugs d ON ffd.id=d.id AND ffd.is_active=d.is_active AND ffd.name=d.name;
	--VALIDATE IF FF SOURCE DATA AND DRUGS MATERIALIZED VIEW HAVE THE SAME RECORDS
	IF FF_DRUGS_COUNT = FF_DW_MERGED_DRUGS_COUNT THEN
		SUCCESS :=TRUE;
	ELSE
		select throw_error('FF AND DW SCHEMAS CONTAINS DIFFERENT DRUGS');
		SUCCESS:=FALSE; 	
	END IF;
ELSE 
		select throw_error('FF AND DW SCHEMAS CONTAINS DIFFERENT DRUGS');
		SUCCESS:=FALSE; 
END IF;

RETURN SUCCESS;
END
$$ LANGUAGE plpgsql;
