CREATE OR REPLACE FUNCTION validate_providers_data()
RETURNS BOOLEAN AS $$
DECLARE
SUCCESS BOOLEAN DEFAULT FALSE;
FF_PROVIDERS_COUNT INTEGER;
DW_PROVIDERS_COUNT INTEGER;
FE_PROVIDERS_COUNT INTEGER;
FF_DW_MERGED_PROVIDERS_COUNT INTEGER;
FF_FE_MERGED_PROVIDERS_COUNT INTEGER;
BEGIN

  --COUNT THE TOTAL PROVIDERS IN SOURCE DATABASE
  SELECT COUNT(*) INTO FF_PROVIDERS_COUNT FROM ff.providers_import ffpi where ffpi.is_active=TRUE;
  --COUNT THE TOTAL PROVIDERS IN DATAWAREHOUSE DATABASE
  SELECT COUNT(*) INTO DW_PROVIDERS_COUNT FROM ff.providers;
  --COUNT THE TOTAL PROVIDERS IN FE SCHEMA
  SELECT COUNT(*) INTO FE_PROVIDERS_COUNT FROM fe.providers;

   IF FF_PROVIDERS_COUNT = DW_PROVIDERS_COUNT THEN
       SELECT COUNT(*) INTO FF_DW_MERGED_PROVIDERS_COUNT FROM ff.providers_import ffpi JOIN ff.providers ffp ON ffpi.id=ffp.id AND ffpi.is_active = TRUE AND ffpi.is_active=ffp.is_active AND ffpi.name=ffp.name; 
	IF FF_PROVIDERS_COUNT = FF_DW_MERGED_PROVIDERS_COUNT THEN
	    SUCCESS:=TRUE;
	ELSE
	   select throw_error('FF SOURCE DATA AND DATAWAREHOUSE PROVIDERS DONT MATCH');
	END IF;
   ELSE
       select throw_error('FF SOURCE DATA AND DATAWAREHOUSE PROVIDERS DONT MATCH');
   END IF;


   IF FF_PROVIDERS_COUNT = FE_PROVIDERS_COUNT THEN
   SELECT COUNT(*) INTO FF_FE_MERGED_PROVIDERS_COUNT FROM ff.providers_import ffpi JOIN fe.providers fep ON ffpi.id=fep.id AND ffpi.is_active = TRUE AND ffpi.is_active=fep.is_active AND ffpi.name=fep.name; 
	IF FF_PROVIDERS_COUNT = FF_FE_MERGED_PROVIDERS_COUNT THEN
	    SUCCESS:=TRUE;
	ELSE
	   select throw_error('FF SOURCE DATA AND DATAWAREHOUSE FE SCHEMA  PROVIDERS DONT MATCH');
	END IF;
   ELSE
       select throw_error('FF SOURCE DATA AND DATAWAREHOUSE FE SCHEMA PROVIDERS DONT MATCH');
   END IF;
  
  
RETURN SUCCESS;
END
$$ LANGUAGE plpgsql;
