CREATE OR REPLACE FUNCTION validatehealthplansdata()-- FRONT END
RETURNS BOOLEAN AS $$
DECLARE
SUCCESS BOOLEAN DEFAULT FALSE;
FF_HEALTH_PLANS_COUNT INTEGER;-- FF SOURCE DATA HEALTH PLANS COUNT
FE_HEALTH_PLANS_COUNT INTEGER;-- FE SCHEMA HEALTH PLANS COUNT 
FF_FE_MERGED_HEALTH_PLANS_COUNT INTEGER;-- FE FF SOURCE DATA MERGED HEALTH PLANS COUNT
BEGIN
--COUNT HEALTH PLANS IN FF SOURCE DATABASE
SELECT COUNT(*) INTO FF_HEALTH_PLANS_COUNT FROM ff.health_plans_import  hpi WHERE hpi.is_active=TRUE;

--COUNT HEALTH PLANS IN FRONT END HEALTH PLANS MATERIALIZED VIEW
SELECT COUNT(*) INTO FE_HEALTH_PLANS_COUNT FROM health_plans hp;


--IF FRONT END HEALTH PLANS MATERIALIZED VIEW AND FF SOURCE DATA HAVE EQUAL COUNTS
IF FF_HEALTH_PLANS_COUNT = FE_HEALTH_PLANS_COUNT THEN
	SELECT COUNT(*) INTO FF_FE_MERGED_HEALTH_PLANS_COUNT FROM ff.health_plans_import ffhp JOIN health_plans hp ON ffhp.id=hp.id AND ffhp.health_plan_type_id = hp.health_plan_type_id and ffhp.name=hp.name and ffhp.formulary_url = hp.formulary_url and ffhp.formulary_id = hp.formulary_id and ffhp.provider_id = hp.provider_id and ffhp.qualifier_url = hp.qualifier_url;
	--VALIDATE IF FF SOURCE DATA AND FRONT END HEALTH PLANS MATERIALIZED VIEW HAVE THE SAME RECORDS
	IF FF_HEALTH_PLANS_COUNT = FF_FE_MERGED_HEALTH_PLANS_COUNT THEN
		SUCCESS :=TRUE;
	ELSE
		select throw_error('FF SOURCE DATA AND FRONT END HEALTH PLANS MATERIALIZED VIEW CONTAINS DIFFERENT HEALTHPLANS');
		SUCCESS:=FALSE; 	
	END IF;
ELSE
	select throw_error('FF SOURCE DATA AND FRONT END HEALTH PLANS MATERIALIZED VIEW CONTAINS DIFFERENT HEALTHPLANS');
	SUCCESS:=FALSE;
END IF;

RETURN SUCCESS;
END
$$ LANGUAGE plpgsql;